[package]
name = "nonstationary-2-5"
version = "0.1.0"
authors = ["hannagabor <gahanna999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
gnuplot = "0.0.31"
